fweanapp/urls.py
from django.urls import path

from .views import *
from django.conf.urls import handler404
handler404 = error_404_view
from froala_editor import views
app_name = "fweanapp"

urlpatterns = [


path('admin-site/login/', AdminLoginView.as_view(), name = 'adminlogin'),
path('fwean-admin/profile-<int:pk>/',AdminProfileView.as_view(), name="adminprofile"),
path('fwean-admin/<int:pk>/update/', AdminProfileUpdateView.as_view(), name = 'adminprofileupdate'),
path('fwean-admin/changepassword/',AdminPasswordUpdateView.as_view(), name="adminpasswordchange"),
path('logout/', AdminLogoutView.as_view(), name="adminlogout"),
path('admin-dashboard/',AdminDashboardView.as_view(), name = 'admindashboard'),


path('admin/organization/create/', AdminOrganizationCreateView.as_view(), name = 'adminorganizationcreate'),
path('admin/organization/update/<int:pk>/', AdminOrganizationUpdateView.as_view(), name = 'adminorganizationupdate'),
path('admin/organization/detail/<int:pk>/', AdminOrganizationDetailView.as_view(), name = 'adminorganizationdetail'),


path('admin/image-album/add/', ImageAlbumAddView.as_view(), name = 'imagealbumadd'),
path('admin/imagealbum/list/', ImageAlbumListView.as_view(), name = 'imagealbumlist'),
path('admin/imagealbum/<int:pk>/detail/', ImageAlbumDetailView.as_view(), name = 'adminimagealbumdetail'),
path('admin/imagealbum/<int:pk>/update/', ImageAlbumUpdateView.as_view(), name = 'adminimagealbumupdate'),
path('admin/imagealbum/<int:pk>/delete/', ImageAlbumDeleteView.as_view(), name = 'adminimagealbumdelete'),


path('admin/imagemedia/<int:pk>/delete/', ImageMediaDeleteView.as_view(), name = 'adminimagemediadelete'),


path('admin/image-slider/add/', SliderCreateView.as_view(), name = 'adminislidercreate'),
path('admin/image-slider/list/', SliderListView.as_view(), name = 'adminsliderlist'),
path('admin/image-slider/<int:pk>/detail/', SliderDetailView.as_view(), name = 'adminsliderdetail'),
path('admin/image-slider/<int:pk>/update/', AdminSliderUpdateView.as_view(), name = 'adminsliderupdate'),
path('admin/image-slider/<int:pk>/delete/', AdminSliderDeleteView.as_view(), name = 'adminsliderdelete'),




path('admin/aboutus/add/', AdminAboutUsCreateView.as_view(), name = 'adminaboutuscreate'),
path('admin/aboutus/list/', AdminAboutUsListView.as_view(), name = 'adminaboutuslist'),
path('admin/aboutus/<int:pk>/detail/', AdminAboutUsDetailView.as_view(), name = 'adminaboutusdetail'),
path('admin/aboutus/<int:pk>/update/', AdminAboutUsUpdateView.as_view(), name = 'adminaboutusupdate'),
path('admin/aboutus/<int:pk>/delete/', AdminAboutUsDeleteView.as_view(), name = 'adminaboutusdelete'),

#projects
path('admin/project/add/', AdminProjectsCreateView.as_view(), name = 'adminprojectcreate'),
path('admin/project/list/', AdminProjectsListView.as_view(), name = 'adminprojectlist'),
path('admin/project/<int:pk>/detail/', AdminProjectsDetailView.as_view(), name = 'adminprojectdetail'),
path('admin/project/<int:pk>/update/', AdminProjectsUpdateView.as_view(), name = 'adminprojectupdate'),
path('admin/project/<int:pk>/delete/', AdminProjectsDeleteView.as_view(), name = 'adminprojectdelete'),

#programmes
path('admin/programmes/add/', AdminProgrammesCreateView.as_view(), name = 'adminprogrammecreate'),
path('admin/programmes/list/', AdminProgrammesListView.as_view(), name = 'adminprogrammelist'),
path('admin/programmes/<int:pk>/detail/', AdminProgrammesDetailView.as_view(), name = 'adminprogrammedetail'),
path('admin/programmes/<int:pk>/update/', AdminProgrammesUpdateView.as_view(), name = 'adminprogrammeupdate'),
path('admin/programmes/<int:pk>/delete/', AdminProgrammesDeleteView.as_view(), name = 'adminprogrammedelete'),

#successstories
path('admin/success-stories/add/', AdminSuccessStoriesCreateView.as_view(), name = 'adminsuccessstoriescreate'),
path('admin/success-stories/list/', AdminSuccessStoriesListView.as_view(), name = 'adminsuccessstorieslist'),
path('admin/success-stories/<int:pk>/detail/', AdminSuccessStoriesDetailView.as_view(), name = 'adminsuccessstoriesdetail'),
path('admin/success-stories/<int:pk>/update/', AdminSuccessStoriesUpdateView.as_view(), name = 'adminsuccessstoriesupdate'),
path('admin/success-stories/<int:pk>/delete/', AdminSuccessStoriesDeleteView.as_view(), name = 'adminsuccessstoriesdelete'),

#Subscriber

path('admin/subscribers/', AdminSubscribersListView.as_view(), name = 'adminsubscriberlist'),
path('admin/subscriber/<int:pk>/delete/', AdminSubscriberDeleteView.as_view(), name = 'adminsubscriberdelete'),
path('admin/subscriber/<int:pk>/update/', AdminSubscriberUpdateView.as_view(), name = 'adminsubscriberupdate'),

#Blog
path('admin/blog/add/', AdminBlogCreateView.as_view(), name = 'adminblogcreate'),
path('admin/blog/list/', AdminBlogListView.as_view(), name = 'adminbloglist'),
path('admin/blog/<int:pk>/detail/', AdminBlogDetailView.as_view(), name = 'adminblogdetail'),
path('admin/blog/<int:pk>/update/', AdminBlogUpdateView.as_view(), name = 'adminblogupdate'),
path('admin/blog/<int:pk>/delete/', AdminBlogDeleteView.as_view(), name = 'adminblogdelete'),


#Donors
path('admin/donor/add/', AdminDonorsCreateView.as_view(), name = 'admindonorcreate'),
path('admin/donor/list/', AdminDonorsListView.as_view(), name = 'admindonorlist'),
path('admin/donor/<int:pk>/detail/', AdminDonorsDetailView.as_view(), name = 'admindonordetail'),
path('admin/donor/<int:pk>/update/', AdminDonorsUpdateView.as_view(), name = 'admindonorupdate'),
path('admin/donor/<int:pk>/delete/', AdminDonorsDeleteView.as_view(), name = 'admindonordelete'),

#Faq
path('admin/faq/add/', AdminFAQCreateView.as_view(), name = 'adminfaqcreate'),
path('admin/faq/list/', AdminFAQListView.as_view(), name = 'adminfaqlist'),
path('admin/faq/<int:pk>/detail/', AdminFAQDetailView.as_view(), name = 'adminfaqdetail'),
path('admin/faq/<int:pk>/update/', AdminFAQUpdateView.as_view(), name = 'adminfaqupdate'),
path('admin/faq/<int:pk>/delete/', AdminFAQDeleteView.as_view(), name = 'adminfaqdelete'),

#Important Links

#Faq
path('admin/important-links/add/', AdminImportantLinksCreateView.as_view(), name = 'adminimportantlinkscreate'),
path('admin/important-links/list/', AdminImportantLinksListView.as_view(), name = 'adminimportantlinkslist'),
# path('admin/important-links/<int:pk>/detail/', AdminImportantLinksDetailView.as_view(), name = 'adminfaqdetail'),
path('admin/important-links/<int:pk>/update/', AdminImportantLinksUpdateView.as_view(), name = 'adminimportantlinksupdate'),
path('admin/important-links/<int:pk>/delete/', AdminImportantLinksDeleteView.as_view(), name = 'adminimportantlinksdelete'),



#Upcoming Events
path('admin/upcoming-event/add/', AdminUpcomingEventsCreateView.as_view(), name = 'adminupcomingeventcreate'),
path('admin/upcoming-event/list/', AdminUpcomingEventsListView.as_view(), name = 'adminupcomingeventlist'),
path('admin/upcoming-event/<int:pk>/detail/', AdminUpcomingEventsDetailView.as_view(), name = 'adminupcomingeventdetail'),
path('admin/upcoming-event/<int:pk>/update/', AdminUpcomingEventsUpdateView.as_view(), name = 'adminupcomingeventupdate'),
path('admin/upcoming-event/<int:pk>/delete/', AdminUpcomingEventsDeleteView.as_view(), name = 'adminupcomingeventdelete'),


#News and Media
path('admin/news/add/', AdminNewsandMediaCreateView.as_view(), name = 'adminnewscreate'),
path('admin/news/list/', AdminNewsandMediaListView.as_view(), name = 'adminnewslist'),
path('admin/news/<int:pk>/detail/', AdminNewsandMediaDetailView.as_view(), name = 'adminnewsdetail'),
path('admin/news/<int:pk>/update/', AdminNewsandMediaUpdateView.as_view(), name = 'adminnewsupdate'),
path('admin/news/<int:pk>/delete/', AdminNewsandMediaDeleteView.as_view(), name = 'adminnewsdelete'),



#SocialMedia NewsFeeds
path('admin/socialmedia-newsfeed/add/', AdminSocialMediaNewsCreateView.as_view(), name = 'adminsocialmedia-newsfeedcreate'),
path('admin/socialmedia-newsfeed/list/', AdminSocialMediaNewsListView.as_view(), name = 'adminsocialmedia-newsfeedlist'),
path('admin/socialmedia-newsfeed/<int:pk>/detail/', AdminSocialMediaNewsDetailView.as_view(), name = 'adminsocialmedia-newsfeeddetail'),
path('admin/socialmedia-newsfeed/<int:pk>/update/', AdminSocialMediaNewsUpdateView.as_view(), name = 'adminsocialmedia-newsfeedupdate'),
path('admin/socialmedia-newsfeed/<int:pk>/delete/', AdminSocialMediaNewsDeleteView.as_view(), name = 'adminsocialmedia-newsfeeddelete'),


#Admin Videos
path('admin/videos/add/', AdminVideosCreateView.as_view(), name = 'adminvideocreate'),
path('admin/videos/list/', AdminVideosListView.as_view(), name = 'adminvideolist'),
path('admin/videos/<int:pk>/detail/', AdminVideosDetailView.as_view(), name = 'adminvideodetail'),
path('admin/videos/<int:pk>/update/', AdminVideosUpdateView.as_view(), name = 'adminvideoupdate'),
path('admin/videos/<int:pk>/delete/', AdminVideosDeleteView.as_view(), name = 'adminvideodelete'),


#BoardMembers
path('admin/board-members/add/', AdminBoardMembersAddView.as_view(), name = 'boardmembersadd'),
path('admin/board-members/', AdminBoardMembersListView.as_view(), name = 'adminboardmemberlist'),
path('admin/board-members/<int:pk>/detail/', AdminVideosDetailView.as_view(), name = 'adminboardmembersdetail'),
path('admin/board-members/<int:pk>/update/', AdminBoardMembersUpdateView.as_view(), name = 'adminboardmembersupdate'),
path('admin/board-members/<int:pk>/delete/', AdminVideosDeleteView.as_view(), name = 'aadminvideodelete'),


#Vice Presidents
path('admin/vice-president/add/', BoardVicePresidentsAddView.as_view(), name = 'adminboardvicepresidentadd'),
path('admin/vice-president/list/', BoardVicePresidentslistView.as_view(), name = 'adminboardvicepresidentlist'),
# path('admin/board-members/<int:pk>/detail/', AdminVideosDetailView.as_view(), name = 'adminboardmembersdetail'),
path('admin/vice-president/<int:pk>/update/', BoardVicePresidentsUpdateView.as_view(), name = 'adminvicepresidentupdate'),

fweanproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from froala_editor import views
urlpatterns = [
    path('fwean_admin/', admin.site.urls),
    path('',include('fweanapp.urls')),
    # path('select2/',include('django_select2.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('froala_editor/',include('froala_editor.urls'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminboardmemberdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/admintemplates/adminnoticedetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block css %}
    <link href="{% static 'adminstatic/base/assets/libs/magnific-popup/dist/magnific-popup.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}


            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h3 class="page-title">({{ adminnoticedetail.title }}) detail</h3>
                        <div class="ms-auto text-end">
                            <nav aria-label="breadcrumb">
                                <
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->


                   <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                



                                 <div class="row el-element-overlay">

                


                     <div class="card-action">
                         <hr>
                           <h5> Publication Title:  "{{ adminnoticedetail.title }}" </h5>


                        </div>
                                     
                        <div class="card-action">
                           <h5>Description:</h5>  {{ adminnoticedetail.description|safe }}
                            <hr>
                        </div>

                        <div class="card-action">
                            <h5>Date:</h5>  {{ adminnoticedetail.date }}
                             <hr>
                         </div>
                        </div>

                            </div>
                        </div>
                    </div>

                </div>

            </div>



            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->




{% endblock %}

{% block js %}
{% endblock %}

templates/admintemplates/adminprofileupdate.html
{% extends 'admintemplates/adminbase.html' %}

{% block css %}

{% endblock %}


{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 ml-auto mr-auto">
      <div class="card">
        <div class="card-header card-header-icon card-header-primary">
          <div class="card-icon">

          </div>
          <h4 class="card-title">Edit Profile -
            <small class="category">Complete your profile</small>
          </h4>
        </div>
        <div class="card-body">
            <div class="row pull-right">

             <a href="{% url 'fweanapp:adminpasswordchange'  %}">  <button class=" mb-2 btn btn-warning btn-round" >Change Password</button> </a>
          </div>
                <form method="POST" enctype="multipart/form-data">
          	{% csrf_token %}
            <div class="row">
                <div class="form-group">
                    
                    <h4>{{ org.name }}</h4>
                  </div>
              <div class="col-md-6">
                   <div class="form-group">
                    <label class="bmd-label-floating">Username</label>
                       {{form.username}}
                  </div>
              </div>
              <div class="col-md-6">

                  <div class="form-group">
                    <label class="bmd-label-floating">Email:</label>
                      {{form.email}}
                  </div>

              </div>


            </div>


            <div class="clearfix text-center">  <button type="submit" class="btn btn-success ">Submit</button></div>

          </form>
        </div>
      </div>
    </div>

  </div>
</div>

{% endblock %}


{% block js %}

    <script>

    </script>

{% endblock %}

templates/admintemplates/imagealbumlist.html
{% extends 'admintemplates/adminbase.html' %}

{% block css %}

<style>
body {
	color: #566787;
	background: #f5f5f5;
	font-family: 'Varela Round', sans-serif;
	font-size: 13px;
}
.table-responsive {
    margin: 30px 0;
}
.table-wrapper {
	background: #fff;
	padding: 20px 25px;
	border-radius: 3px;
	min-width: 1000px;
	box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.table-title {
	padding-bottom: 15px;
	background: #435d7d;
	color: #fff;
	padding: 16px 30px;
	min-width: 100%;
	margin: -20px -25px 10px;
	border-radius: 3px 3px 0 0;
}
.table-title h2 {
	margin: 5px 0 0;
	font-size: 24px;
}
.table-title .btn-group {
	float: right;
}
.table-title .btn {
	color: #fff;
	float: right;
	font-size: 13px;
	border: none;
	min-width: 50px;
	border-radius: 2px;
	border: none;
	outline: none !important;
	margin-left: 10px;
}
.table-title .btn i {
	float: left;
	font-size: 21px;
	margin-right: 5px;
}
.table-title .btn span {
	float: left;
	margin-top: 2px;
}
table.table tr th, table.table tr td {
	border-color: #e9e9e9;
	padding: 12px 15px;
	vertical-align: middle;
}
table.table tr th:first-child {
	width: 60px;
}
table.table tr th:last-child {
	width: 100px;
}
table.table-striped tbody tr:nth-of-type(odd) {
	background-color: #fcfcfc;
}
table.table-striped.table-hover tbody tr:hover {
	background: #f5f5f5;
}
table.table th i {
	font-size: 13px;
	margin: 0 5px;
	cursor: pointer;
}
table.table td:last-child i {
	opacity: 0.9;
	font-size: 22px;
	margin: 0 5px;
}
table.table td a {
	font-weight: bold;
	color: #566787;
	display: inline-block;
	text-decoration: none;
	outline: none !important;
}
table.table td a:hover {
	color: #2196F3;
}
table.table td a.edit {
	color: #FFC107;
}
table.table td a.delete {
	color: #F44336;
}
table.table td i {
	font-size: 19px;
}
table.table .avatar {
	border-radius: 50%;
	vertical-align: middle;
	margin-right: 10px;
}
.pagination {
	float: right;
	margin: 0 0 5px;
}
.pagination li a {
	border: none;
	font-size: 13px;
	min-width: 30px;
	min-height: 30px;
	color: #999;
	margin: 0 2px;
	line-height: 30px;
	border-radius: 2px !important;
	text-align: center;
	padding: 0 6px;
}
.pagination li a:hover {
	color: #666;
}
.pagination li.active a, .pagination li.active a.page-link {
	background: #03A9F4;
}
.pagination li.active a:hover {
	background: #0397d6;
}
.pagination li.disabled i {
	color: #ccc;
}
.pagination li i {
	font-size: 16px;
	padding-top: 6px
}
.hint-text {
	float: left;
	margin-top: 10px;
	font-size: 13px;
}
/* Custom checkbox */
.custom-checkbox {
	position: relative;
}
.custom-checkbox input[type="checkbox"] {
	opacity: 0;
	position: absolute;
	margin: 5px 0 0 3px;
	z-index: 9;
}
.custom-checkbox label:before{
	width: 18px;
	height: 18px;
}
.custom-checkbox label:before {
	content: '';
	margin-right: 10px;
	display: inline-block;
	vertical-align: text-top;
	background: white;
	border: 1px solid #bbb;
	border-radius: 2px;
	box-sizing: border-box;
	z-index: 2;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	content: '';
	position: absolute;
	left: 6px;
	top: 3px;
	width: 6px;
	height: 11px;
	border: solid #000;
	border-width: 0 3px 3px 0;
	transform: inherit;
	z-index: 3;
	transform: rotateZ(45deg);
}
.custom-checkbox input[type="checkbox"]:checked + label:before {
	border-color: #03A9F4;
	background: #03A9F4;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	border-color: #fff;
}
.custom-checkbox input[type="checkbox"]:disabled + label:before {
	color: #b8b8b8;
	cursor: auto;
	box-shadow: none;
	background: #ddd;
}
/* Modal styles */
.modal .modal-dialog {
	max-width: 400px;
}
.modal .modal-header, .modal .modal-body, .modal .modal-footer {
	padding: 20px 30px;
}
.modal .modal-content {
	border-radius: 3px;
	font-size: 14px;
}
.modal .modal-footer {
	background: #ecf0f1;
	border-radius: 0 0 3px 3px;
}
.modal .modal-title {
	display: inline-block;
}
.modal .form-control {
	border-radius: 2px;
	box-shadow: none;
	border-color: #dddddd;
}
.modal textarea.form-control {
	resize: vertical;
}
.modal .btn {
	border-radius: 2px;
	min-width: 100px;
}
.modal form label {
	font-weight: normal;
}
</style>


{% endblock %}

{% block content %}


    <div class="container-xl">
	<div class="table-responsive">
		<div class="table-wrapper">
          <div class="col-md-6 text-center col-lg-12 col-xlg-3">
                                        <a href="{% url 'fweanapp:adminvideolist' %}">
                                       <button style="background: darkred" class="btn btn-lg btn-primary">+ Videos</button>
                                        </a>
                                    </div>
			<div class="table-title">
				<div class="row">
					<div class="col-sm-6">
						<h2>Manage <b>Albums (Gallery)</b></h2>
					</div>
					<div class="col-sm-6">
                        <a href="{% url 'fweanapp:imagealbumadd' %}"><div class="btn btn-success" data-toggle="modal"><i class="fas fa-plus-circle">&#xE147;</i> <span>Add New Album</span></div></a>
{#						<a href="#deleteEmployeeModal" class="btn btn-danger" data-toggle="modal"><i class="fas fa-minus-circle">&#xE15C;</i> <span>Delete</span></a>#}

                    </div>
				</div>
			</div>
			<table id="example" class="table table-striped table-hover" style="width: 100%">
				<thead>
					<tr class="h4 header">

						<th>S.N</th>
						<th>Title</th>
						<th>Album Thumbnail</th>
{#						<th>Description</th>#}
						<th>Details</th>
						<th>Publish</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
                         {% for album in albums %}

                      <tr>

						<td>{{ forloop.counter}}.</td>
						<td>{{ album.title}}</td>
						<td><img style="width: 50px; height: 40px;" src="{{ album.image.url }}" alt=""></td>
{#						<td>{{ album.description}}</td>#}

                           <td>
                                                    <a href="{% url 'fweanapp:adminimagealbumdetail' album.id %}"><button class="btn btn-sm btn-success">View Details</button></a>
                                        </td>
                          <td>{% if album.is_active %}
                          <i style="color: limegreen" class="fa fa-check"></i>
                          {% else %}
                           <i style="color: red" class="fa fa-times"></i>

                      {% endif %} </td>
						<td>
							<a href="{% url 'fweanapp:adminimagealbumupdate' album.id %}"><i class="fas fa-pencil-alt" title="Edit">&#xE254;</i></a>
							<a href="#deleteEmployeeModal{{ album.id }}" class="delete" data-toggle="modal"><i class="fas fa-trash" title="Delete">&#xE872;</i></a>
						</td>
					</tr>

                {% endfor %}
				</tbody>
			</table>

		</div>
	</div>
</div>
<!-- Edit Modal HTML -->
<div id="addEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">
					<h4 class="modal-title">Add Employee</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Name</label>
						<input type="text" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Address</label>
						<textarea class="form-control" required></textarea>
					</div>
					<div class="form-group">
						<label>Phone</label>
						<input type="text" class="form-control" required>
					</div>
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-success" value="Add">
				</div>
			</form>
		</div>
	</div>
</div>
<!-- Edit Modal HTML -->

<!-- Delete Modal HTML -->
     {% for album in albums %}
<div id="deleteEmployeeModal{{ album.id }}" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">
					<h4 class="modal-title">Delete Album</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<p>Are you sure you want to delete the album {{ album.title }}</p>
					<p class="text-warning"><small>This action cannot be undone.</small></p>
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<button  class="btn btn-danger"> <a href="{% url 'fweanapp:adminimagealbumdelete' album.id %}"> Delete </a> </button>
				</div>
			</form>
		</div>
	</div>
</div>
    {% endfor %}


{% endblock %}

{% block js %}


{% endblock %}